apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic
    app.kubernetes.io/part-of: load-app-767aeeb5-a0fd-41a6-9825-b1cc06f3b6de
  name: devfile-sample-go-basic
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-sample-go-basic
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-sample-go-basic
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-39-tenant/load-app-767aeeb5-a0fd-41a6-9825-b1cc06f3b6de/devfile-sample-go-basic@sha256:e53727c26d655ba41d2b20238e42fd3320baea6e7dda74998320e4cf6bd364be
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
